apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service
          image: 640083577712.dkr.ecr.us-east-1.amazonaws.com/healthcare-production-authentication-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: AUTHENTICATION_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: AUTHENTICATION_DB_URL
              value: jdbc:postgresql://db-auth:5432/AuthenticationService
            - name: AUTHENTICATION_DB_USERNAME
              value: postgres
            - name: AUTHENTICATION_DB_PASSWORD
              value: alwis
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-registry:8761/eureka
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_CLIENT_ENABLED
              value: "true"