apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: 640083577712.dkr.ecr.us-east-1.amazonaws.com/healthcare-production-service-registry:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8761